project:
  type: website
  output-dir: docs

website:
  title: "Fan Yang - MUSA 5080"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4"
          - href: weekly-notes/week-05-notes.qmd
            text: "Week 5"
      - text: "Labs"
        menu:
          - href: labs/lab_setup_instructions.qmd
            text: "Lab 1: Setup Instructions"
          - href: labs/lab_0/lab0_index.qmd
            text: "Lab 2: Getting Started with dplyr"
          - href: labs/lab_3/week3_lab_exercise.qmd
            text: "Lab 3: Data Visualization and EDA"
          - href: labs/lab_4/week4_inclass_practice.qmd
            text: "Lab 4: Spatial Operations with Pennsylvania Data"
      - text: "Assignments"
        menu:
          - href: assignments/assignment_1/Fan_Yang_Assignment1.qmd
            text: "Assignment 1: Census Data Quality for Policy Decisions"
          - href: assignments/assignment_2/Fan_Yang_Assignment2.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
      - text: "Midterm Challenge"
        menu:
          - href: Midterm/Yang_Chen_Fang_Gao_Xiang_Zhao_Appendix.qmd
            text: "Midterm Appendix"
          - href: Midterm/Yang_Chen_Fang_Gao_Xiang_Zhao_Presentation.qmd
            text: "Midterm Presentation"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    css: styles.css
    page-layout: full

execute:
  freeze: auto
