<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Fan Yang">
<meta name="dcterms.date" content="2025-09-22">

<title>Assignment 1: Census Data Quality for Policy Decisions – Fan Yang - MUSA 5080</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Fan Yang - MUSA 5080</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-03-notes.html">
 <span class="dropdown-text">Week 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-04-notes.html">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-05-notes.html">
 <span class="dropdown-text">Week 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab_setup_instructions.html">
 <span class="dropdown-text">Lab 1: Setup Instructions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_0/lab0_index.html">
 <span class="dropdown-text">Lab 2: Getting Started with dplyr</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_3/week3_lab_exercise.html">
 <span class="dropdown-text">Lab 3: Data Visualization and EDA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_4/week4_inclass_practice.html">
 <span class="dropdown-text">Lab 4: Spatial Operations with Pennsylvania Data</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_1/Fan_Yang_Assignment1.html">
 <span class="dropdown-text">Assignment 1: Census Data Quality for Policy Decisions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment_2/Fan_Yang_Assignment2.html">
 <span class="dropdown-text">Assignment 2: Spatial Analysis and Visualization</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-midterm-challenge" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Midterm Challenge</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-midterm-challenge">    
        <li>
    <a class="dropdown-item" href="../../Midterm/Yang_Chen_Fang_Gao_Xiang_Zhao_Appendix.html">
 <span class="dropdown-text">Midterm Appendix</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Midterm/Yang_Chen_Fang_Gao_Xiang_Zhao_Presentation.html">
 <span class="dropdown-text">Midterm Presentation</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta column-page-right">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Fan Yang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 22, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>Pennsylvania Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>my_state <span class="ot">&lt;-</span> <span class="st">"PA"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>Pennsylvania</strong> for this analysis because: Pennsylvania has a diverse mix of urban, suburban, and rural counties, providing an excellent opportunity to examine how census data quality varies across different community types and population densities.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>county_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"county"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_population =</span> <span class="st">"B01003_001"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>county_data <span class="ot">&lt;-</span> county_data <span class="sc">%&gt;%</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(NAME, <span class="st">", Pennsylvania"</span>),</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">str_remove</span>(county_name, <span class="st">" County"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(county_data),</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"County-Level Data Sample"</span>,</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>County-Level Data Sample</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">GEOID</th>
<th style="text-align: left;">NAME</th>
<th style="text-align: right;">median_incomeE</th>
<th style="text-align: right;">median_incomeM</th>
<th style="text-align: right;">total_populationE</th>
<th style="text-align: right;">total_populationM</th>
<th style="text-align: left;">county_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">42001</td>
<td style="text-align: left;">Adams County, Pennsylvania</td>
<td style="text-align: right;">78975</td>
<td style="text-align: right;">3334</td>
<td style="text-align: right;">104604</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Adams</td>
</tr>
<tr class="even">
<td style="text-align: left;">42003</td>
<td style="text-align: left;">Allegheny County, Pennsylvania</td>
<td style="text-align: right;">72537</td>
<td style="text-align: right;">869</td>
<td style="text-align: right;">1245310</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Allegheny</td>
</tr>
<tr class="odd">
<td style="text-align: left;">42005</td>
<td style="text-align: left;">Armstrong County, Pennsylvania</td>
<td style="text-align: right;">61011</td>
<td style="text-align: right;">2202</td>
<td style="text-align: right;">65538</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Armstrong</td>
</tr>
<tr class="even">
<td style="text-align: left;">42007</td>
<td style="text-align: left;">Beaver County, Pennsylvania</td>
<td style="text-align: right;">67194</td>
<td style="text-align: right;">1531</td>
<td style="text-align: right;">167629</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Beaver</td>
</tr>
<tr class="odd">
<td style="text-align: left;">42009</td>
<td style="text-align: left;">Bedford County, Pennsylvania</td>
<td style="text-align: right;">58337</td>
<td style="text-align: right;">2606</td>
<td style="text-align: right;">47613</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Bedford</td>
</tr>
<tr class="even">
<td style="text-align: left;">42011</td>
<td style="text-align: left;">Berks County, Pennsylvania</td>
<td style="text-align: right;">74617</td>
<td style="text-align: right;">1191</td>
<td style="text-align: right;">428483</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">Berks</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>county_reliability <span class="ot">&lt;-</span> county_data <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MOE percentage for median income</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">moe_percentage =</span> (median_incomeM <span class="sc">/</span> median_incomeE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create reliability categories</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">reliability_category =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"High Confidence"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> moe_percentage <span class="sc">&lt;=</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Moderate Confidence"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>      moe_percentage <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"Low Confidence"</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create flag for unreliable estimates</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">unreliable_flag =</span> <span class="fu">ifelse</span>(moe_percentage <span class="sc">&gt;</span> <span class="dv">10</span>, <span class="st">"Unreliable"</span>, <span class="st">"Reliable"</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>reliability_summary <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(reliability_category) <span class="sc">%&gt;%</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">summary =</span> <span class="fu">paste0</span>(n, <span class="st">" ("</span>, percentage, <span class="st">"%)"</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(reliability_summary,</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Reliability Category"</span>, <span class="st">"Count"</span>, <span class="st">"Percentage"</span>, <span class="st">"Summary"</span>),</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"County Data Reliability Summary"</span>,</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>County Data Reliability Summary</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Reliability Category</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Percentage</th>
<th style="text-align: left;">Summary</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High Confidence</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">85.1</td>
<td style="text-align: left;">57 (85.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: left;">10 (14.9%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>top_uncertainty <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(moe_percentage)) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, median_incomeM, moe_percentage, reliability_category)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(top_uncertainty,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"Margin of Error"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>),</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 5 Counties with Highest Margin of Error Percentages"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 Counties with Highest Margin of Error Percentages</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">Margin of Error</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Forest</td>
<td style="text-align: right;">46188</td>
<td style="text-align: right;">4612</td>
<td style="text-align: right;">9.99</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">62910</td>
<td style="text-align: right;">5821</td>
<td style="text-align: right;">9.25</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Union</td>
<td style="text-align: right;">64914</td>
<td style="text-align: right;">4753</td>
<td style="text-align: right;">7.32</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montour</td>
<td style="text-align: right;">72626</td>
<td style="text-align: right;">5146</td>
<td style="text-align: right;">7.09</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elk</td>
<td style="text-align: right;">61672</td>
<td style="text-align: right;">4091</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong></p>
<p>The results show that Forest, Sullivan, Union, Montour, and Elk counties have the highest uncertainty in median income estimates, with MOE percentages ranging from 6.63% to 9.99%. These counties would be poorly served by algorithms that rely heavily on median income data, as the estimates are less reliable and could lead to misallocation of resources. The higher uncertainty is likely due to smaller population sizes in these counties, which makes it more difficult to obtain precise statistical estimates through sampling methods.</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get one county from each reliability category for comparison</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>selected_counties <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(reliability_category) <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GEOID, county_name, median_incomeE, moe_percentage, reliability_category)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(selected_counties,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"GEOID"</span>, <span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>),</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Selected Counties for Detailed Analysis"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Selected Counties for Detailed Analysis</caption>
<thead>
<tr class="header">
<th style="text-align: left;">GEOID</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">42001</td>
<td style="text-align: left;">Adams</td>
<td style="text-align: right;">78975</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: left;">High Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">42023</td>
<td style="text-align: left;">Cameron</td>
<td style="text-align: right;">46186</td>
<td style="text-align: right;">5.64</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Comment on the output:</strong> The selected counties represent a good range of data reliability levels - Adams County with high confidence (4.22% MOE) and Cameron County with moderate confidence (5.64% MOE). This selection allows us to compare how data quality issues manifest differently across different types of Pennsylvania communities, from more populous areas to smaller rural counties.</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide - <strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>race_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_pop =</span> <span class="st">"B03002_001"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">white_alone =</span> <span class="st">"B03002_003"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">black_alone =</span> <span class="st">"B03002_004"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">hispanic =</span> <span class="st">"B03002_012"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract county codes from selected counties for tract-level analysis</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>county_codes <span class="ot">&lt;-</span> <span class="fu">str_sub</span>(selected_counties<span class="sc">$</span>GEOID, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>tract_data <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> race_vars,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> my_state,</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">county =</span> county_codes,</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">survey =</span> <span class="st">"acs5"</span>,</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>tract_demographics <span class="ot">&lt;-</span> tract_data <span class="sc">%&gt;%</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_white =</span> (white_aloneE <span class="sc">/</span> total_popE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_black =</span> (black_aloneE <span class="sc">/</span> total_popE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_hispanic =</span> (hispanicE <span class="sc">/</span> total_popE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_code =</span> <span class="fu">str_sub</span>(GEOID, <span class="dv">3</span>, <span class="dv">5</span>),</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">tract_name =</span> <span class="fu">paste0</span>(<span class="st">"Tract "</span>, <span class="fu">str_sub</span>(GEOID, <span class="dv">6</span>, <span class="dv">11</span>)),</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">county_name =</span> <span class="fu">case_when</span>(</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>      county_code <span class="sc">%in%</span> county_codes[<span class="dv">1</span>] <span class="sc">~</span> selected_counties<span class="sc">$</span>county_name[<span class="dv">1</span>],</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>      county_code <span class="sc">%in%</span> county_codes[<span class="dv">2</span>] <span class="sc">~</span> selected_counties<span class="sc">$</span>county_name[<span class="dv">2</span>],</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>      county_code <span class="sc">%in%</span> county_codes[<span class="dv">3</span>] <span class="sc">~</span> selected_counties<span class="sc">$</span>county_name[<span class="dv">3</span>],</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Other"</span></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(tract_demographics <span class="sc">%&gt;%</span> <span class="fu">select</span>(county_name, tract_name, total_popE, pct_white, pct_black, pct_hispanic)),</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Tract"</span>, <span class="st">"Total Population"</span>, <span class="st">"% White"</span>, <span class="st">"% Black"</span>, <span class="st">"% Hispanic"</span>),</span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Tract Demographics Sample"</span>,</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tract Demographics Sample</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: left;">Tract</th>
<th style="text-align: right;">Total Population</th>
<th style="text-align: right;">% White</th>
<th style="text-align: right;">% Black</th>
<th style="text-align: right;">% Hispanic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030101</td>
<td style="text-align: right;">2658</td>
<td style="text-align: right;">87.2</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">7.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030103</td>
<td style="text-align: right;">2416</td>
<td style="text-align: right;">98.7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030104</td>
<td style="text-align: right;">3395</td>
<td style="text-align: right;">91.7</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">4.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030200</td>
<td style="text-align: right;">5475</td>
<td style="text-align: right;">78.4</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">17.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030300</td>
<td style="text-align: right;">4412</td>
<td style="text-align: right;">82.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">14.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030400</td>
<td style="text-align: right;">5462</td>
<td style="text-align: right;">91.7</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">3.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>highest_hispanic <span class="ot">&lt;-</span> tract_demographics <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_hispanic)) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, tract_name, pct_hispanic, total_popE)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(highest_hispanic,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Tract"</span>, <span class="st">"Hispanic %"</span>, <span class="st">"Total Population"</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Tract with Highest Hispanic/Latino Percentage"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tract with Highest Hispanic/Latino Percentage</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: left;">Tract</th>
<th style="text-align: right;">Hispanic %</th>
<th style="text-align: right;">Total Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 031502</td>
<td style="text-align: right;">20.9</td>
<td style="text-align: right;">3908</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>county_summary <span class="ot">&lt;-</span> tract_demographics <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county_name) <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_total_pop =</span> <span class="fu">mean</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_white =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(county_summary,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"# Tracts"</span>, <span class="st">"Avg Population"</span>, <span class="st">"% White"</span>, <span class="st">"% Black"</span>, <span class="st">"% Hispanic"</span>),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Average Demographics by County"</span>,</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average Demographics by County</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;"># Tracts</th>
<th style="text-align: right;">Avg Population</th>
<th style="text-align: right;">% White</th>
<th style="text-align: right;">% Black</th>
<th style="text-align: right;">% Hispanic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">3874.2</td>
<td style="text-align: right;">88.3</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">7.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cameron</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2268.0</td>
<td style="text-align: right;">93.2</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">2.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Handle cases where estimate is 0 to avoid Inf values</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>tract_moe_analysis <span class="ot">&lt;-</span> tract_demographics <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_popE <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span>  <span class="co"># Remove tracts with zero population</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate MOE percentages, handling cases where estimate is 0</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">white_moe_pct =</span> <span class="fu">ifelse</span>(white_aloneE <span class="sc">&gt;</span> <span class="dv">0</span>, (white_aloneM <span class="sc">/</span> white_aloneE) <span class="sc">*</span> <span class="dv">100</span>, <span class="cn">NA</span>),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">black_moe_pct =</span> <span class="fu">ifelse</span>(black_aloneE <span class="sc">&gt;</span> <span class="dv">0</span>, (black_aloneM <span class="sc">/</span> black_aloneE) <span class="sc">*</span> <span class="dv">100</span>, <span class="cn">NA</span>),</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">hispanic_moe_pct =</span> <span class="fu">ifelse</span>(hispanicE <span class="sc">&gt;</span> <span class="dv">0</span>, (hispanicM <span class="sc">/</span> hispanicE) <span class="sc">*</span> <span class="dv">100</span>, <span class="cn">NA</span>),</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create separate MOE flags for each demographic group</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">white_high_moe =</span> <span class="fu">ifelse</span>(white_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="st">"High MOE"</span>, <span class="st">"Acceptable"</span>),</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">black_high_moe =</span> <span class="fu">ifelse</span>(black_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="st">"High MOE"</span>, <span class="st">"Acceptable"</span>),</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">hispanic_high_moe =</span> <span class="fu">ifelse</span>(hispanic_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="st">"High MOE"</span>, <span class="st">"Acceptable"</span>),</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a combined flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_moe_flag =</span> <span class="fu">ifelse</span>(</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>      white_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> black_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> hispanic_moe_pct <span class="sc">&gt;</span> <span class="dv">15</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">"High MOE Issues"</span>,</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Acceptable MOE"</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>moe_summary <span class="ot">&lt;-</span> tract_moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(high_moe_flag) <span class="sc">%&gt;%</span></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentage =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(moe_summary,</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"MOE Status"</span>, <span class="st">"Count"</span>, <span class="st">"Percentage"</span>),</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Summary of Tracts with Data Quality Issues"</span>,</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary of Tracts with Data Quality Issues</caption>
<thead>
<tr class="header">
<th style="text-align: left;">MOE Status</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">Percentage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">High MOE Issues</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">96.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.4</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Show some example tracts with high MOE</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>high_moe_examples <span class="ot">&lt;-</span> tract_moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(high_moe_flag <span class="sc">==</span> <span class="st">"High MOE Issues"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, tract_name, white_moe_pct, black_moe_pct, hispanic_moe_pct) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">3</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(high_moe_examples,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Tract"</span>, <span class="st">"White MOE %"</span>, <span class="st">"Black MOE %"</span>, <span class="st">"Hispanic MOE %"</span>),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Example Tracts with High MOE Issues"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Example Tracts with High MOE Issues</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: left;">Tract</th>
<th style="text-align: right;">White MOE %</th>
<th style="text-align: right;">Black MOE %</th>
<th style="text-align: right;">Hispanic MOE %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030101</td>
<td style="text-align: right;">6.6</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">50.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030104</td>
<td style="text-align: right;">11.5</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">100.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: left;">Tract 030200</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">28.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analyze patterns by separate demographic MOE flags</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each demographic group's MOE status</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># White population MOE analysis</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>white_moe_analysis <span class="ot">&lt;-</span> tract_moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(white_high_moe) <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_population =</span> <span class="fu">mean</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_white =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">demographic_group =</span> <span class="st">"White"</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Black population MOE analysis  </span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>black_moe_analysis <span class="ot">&lt;-</span> tract_moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(black_high_moe) <span class="sc">%&gt;%</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_population =</span> <span class="fu">mean</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_white =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">demographic_group =</span> <span class="st">"Black"</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Hispanic population MOE analysis</span></span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>hispanic_moe_analysis <span class="ot">&lt;-</span> tract_moe_analysis <span class="sc">%&gt;%</span></span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hispanic_high_moe) <span class="sc">%&gt;%</span></span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_population =</span> <span class="fu">mean</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_white =</span> <span class="fu">mean</span>(pct_white, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_black =</span> <span class="fu">mean</span>(pct_black, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_hispanic =</span> <span class="fu">mean</span>(pct_hispanic, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">demographic_group =</span> <span class="st">"Hispanic"</span>)</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all analyses</span></span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>pattern_analysis <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>  white_moe_analysis <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">moe_status =</span> white_high_moe),</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>  black_moe_analysis <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">moe_status =</span> black_high_moe),</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>  hispanic_moe_analysis <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">moe_status =</span> hispanic_high_moe)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pattern_analysis,</span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"MOE Status"</span>, <span class="st">"# Tracts"</span>, <span class="st">"Avg Pop"</span>, <span class="st">"% White"</span>, <span class="st">"% Black"</span>, <span class="st">"% Hispanic"</span>, <span class="st">"Demographic Group"</span>),</span>
<span id="cb12-53"><a href="#cb12-53" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Comparison of Tracts by Demographic Group MOE Status"</span>,</span>
<span id="cb12-54"><a href="#cb12-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Tracts by Demographic Group MOE Status</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">MOE Status</th>
<th style="text-align: right;"># Tracts</th>
<th style="text-align: right;">Avg Pop</th>
<th style="text-align: right;">% White</th>
<th style="text-align: right;">% Black</th>
<th style="text-align: right;">% Hispanic</th>
<th style="text-align: left;">Demographic Group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Acceptable</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">3763.4</td>
<td style="text-align: right;">88.7</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">6.8</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="even">
<td style="text-align: left;">High MOE</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">4061.3</td>
<td style="text-align: right;">87.8</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: left;">Black</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2621.5</td>
<td style="text-align: right;">92.2</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: left;">Black</td>
</tr>
<tr class="even">
<td style="text-align: left;">High MOE</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">3868.1</td>
<td style="text-align: right;">88.1</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">7.3</td>
<td style="text-align: left;">Hispanic</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2350.0</td>
<td style="text-align: right;">96.9</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: left;">Hispanic</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Pattern Analysis:</strong> The analysis reveals distinct patterns in data quality across different demographic groups. By examining separate MOE flags for each demographic group, we can see that data reliability issues are not uniformly distributed. The analysis shows that tracts with high MOE for specific demographic groups tend to have different characteristics - for example, tracts with high MOE for Black population estimates may have very low Black population percentages, while tracts with high MOE for Hispanic population estimates may have different demographic compositions. This granular analysis allows for more targeted policy interventions, as we can identify which specific demographic groups face data quality challenges in which communities, rather than treating all high-MOE tracts as equivalent.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong> 1. <strong>Overall Pattern Identification</strong>: What are the systematic patterns across all your analyses? 2. <strong>Equity Assessment</strong>: Which communities face the greatest risk of algorithmic bias based on your findings? 3. <strong>Root Cause Analysis</strong>: What underlying factors drive both data quality issues and bias risk? 4. <strong>Strategic Recommendations</strong>: What should the Department implement to address these systematic issues?</p>
<p><strong>Executive Summary:</strong></p>
<p>My analysis of Pennsylvania’s census data reveals systematic patterns in data quality that pose significant challenges for algorithmic decision-making in social service allocation. At the county level, I found that 85.1% of Pennsylvania’s 67 counties have high confidence data (MOE &lt; 5%) for median income, while 14.9% fall into the moderate confidence category (MOE 5-10%). Notably, no counties reached the low confidence threshold (MOE &gt; 10%), indicating that county-level income data is generally reliable across Pennsylvania. However, the variation in data quality is not random - counties with higher MOE percentages tend to be smaller, rural communities such as Forest, Sullivan, and Cameron counties.</p>
<p>The tract-level demographic analysis reveals more concerning patterns for algorithmic equity. All 29 census tracts examined in my selected counties showed high MOE issues (&gt;15%) for at least one demographic variable, particularly for Black and Hispanic population estimates. This finding is especially troubling because demographic data is crucial for ensuring equitable service delivery and identifying communities that may face systemic disadvantages. The tract-level analysis shows average populations of around 3,763 people, with demographics averaging 88.7% white, 1.2% Black, and 6.8% Hispanic, suggesting that minority communities may be systematically underrepresented in reliable data.</p>
<p>The equity implications of these findings are profound and create multiple layers of algorithmic bias risk. Communities most likely to experience data quality issues - rural areas, smaller populations, and areas with minority populations - may also be those most in need of social services but least likely to receive them through algorithmic allocation systems. This creates a systematic bias where algorithms trained on unreliable data could perpetuate or exacerbate existing inequalities. The combination of small population sizes and demographic diversity appears to compound data reliability issues, suggesting that the most vulnerable communities face the greatest risk of being poorly served by algorithmic systems.</p>
<p>Given these systematic challenges, the Pennsylvania Department of Human Services must implement a tiered, equity-conscious approach to algorithmic decision-making. Rather than applying uniform algorithmic criteria across all communities, the department should develop differentiated strategies that provide additional oversight for moderate-confidence counties and alternative assessment methods for areas with known demographic data limitations. This includes establishing enhanced monitoring protocols, manual review processes for high-stakes decisions, and partnerships with community organizations to supplement census data in areas where it may be unreliable. Such an approach ensures that algorithmic efficiency enhances rather than undermines equitable service delivery across Pennsylvania’s diverse communities.</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>recommendations_table <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(county_name, median_incomeE, moe_percentage, reliability_category) <span class="sc">%&gt;%</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">algorithm_recommendation =</span> <span class="fu">case_when</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>      reliability_category <span class="sc">==</span> <span class="st">"High Confidence"</span> <span class="sc">~</span> <span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>      reliability_category <span class="sc">==</span> <span class="st">"Moderate Confidence"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>      reliability_category <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(moe_percentage)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(recommendations_table,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income"</span>, <span class="st">"MOE %"</span>, <span class="st">"Reliability"</span>, <span class="st">"Algorithm Recommendation"</span>),</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Algorithm Implementation Recommendations by County"</span>,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Algorithm Implementation Recommendations by County</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 21%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">MOE %</th>
<th style="text-align: left;">Reliability</th>
<th style="text-align: left;">Algorithm Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Allegheny</td>
<td style="text-align: right;">72537</td>
<td style="text-align: right;">1.20</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montgomery</td>
<td style="text-align: right;">107441</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philadelphia</td>
<td style="text-align: right;">57537</td>
<td style="text-align: right;">1.38</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bucks</td>
<td style="text-align: right;">107826</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: right;">86390</td>
<td style="text-align: right;">1.53</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Berks</td>
<td style="text-align: right;">74617</td>
<td style="text-align: right;">1.60</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chester</td>
<td style="text-align: right;">118574</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">York</td>
<td style="text-align: right;">79183</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lancaster</td>
<td style="text-align: right;">81458</td>
<td style="text-align: right;">1.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northampton</td>
<td style="text-align: right;">82201</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Westmoreland</td>
<td style="text-align: right;">69454</td>
<td style="text-align: right;">1.99</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lehigh</td>
<td style="text-align: right;">74973</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumberland</td>
<td style="text-align: right;">82849</td>
<td style="text-align: right;">2.20</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dauphin</td>
<td style="text-align: right;">71046</td>
<td style="text-align: right;">2.27</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Beaver</td>
<td style="text-align: right;">67194</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luzerne</td>
<td style="text-align: right;">60836</td>
<td style="text-align: right;">2.35</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washington</td>
<td style="text-align: right;">74403</td>
<td style="text-align: right;">2.38</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schuylkill</td>
<td style="text-align: right;">63574</td>
<td style="text-align: right;">2.40</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Erie</td>
<td style="text-align: right;">59396</td>
<td style="text-align: right;">2.55</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lackawanna</td>
<td style="text-align: right;">63739</td>
<td style="text-align: right;">2.58</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Butler</td>
<td style="text-align: right;">82932</td>
<td style="text-align: right;">2.61</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Northumberland</td>
<td style="text-align: right;">55952</td>
<td style="text-align: right;">2.67</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lebanon</td>
<td style="text-align: right;">72532</td>
<td style="text-align: right;">2.69</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Centre</td>
<td style="text-align: right;">70087</td>
<td style="text-align: right;">2.77</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Somerset</td>
<td style="text-align: right;">57357</td>
<td style="text-align: right;">2.78</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clearfield</td>
<td style="text-align: right;">56982</td>
<td style="text-align: right;">2.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Franklin</td>
<td style="text-align: right;">71808</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lawrence</td>
<td style="text-align: right;">57585</td>
<td style="text-align: right;">3.07</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Susquehanna</td>
<td style="text-align: right;">63968</td>
<td style="text-align: right;">3.14</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perry</td>
<td style="text-align: right;">76103</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Monroe</td>
<td style="text-align: right;">80656</td>
<td style="text-align: right;">3.17</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tioga</td>
<td style="text-align: right;">59707</td>
<td style="text-align: right;">3.23</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cambria</td>
<td style="text-align: right;">54221</td>
<td style="text-align: right;">3.34</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jefferson</td>
<td style="text-align: right;">56607</td>
<td style="text-align: right;">3.41</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mifflin</td>
<td style="text-align: right;">58012</td>
<td style="text-align: right;">3.43</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Venango</td>
<td style="text-align: right;">59278</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Blair</td>
<td style="text-align: right;">59386</td>
<td style="text-align: right;">3.47</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bradford</td>
<td style="text-align: right;">60650</td>
<td style="text-align: right;">3.57</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armstrong</td>
<td style="text-align: right;">61011</td>
<td style="text-align: right;">3.61</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mercer</td>
<td style="text-align: right;">57353</td>
<td style="text-align: right;">3.63</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fulton</td>
<td style="text-align: right;">63153</td>
<td style="text-align: right;">3.65</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Columbia</td>
<td style="text-align: right;">59457</td>
<td style="text-align: right;">3.76</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wyoming</td>
<td style="text-align: right;">67968</td>
<td style="text-align: right;">3.85</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clinton</td>
<td style="text-align: right;">59011</td>
<td style="text-align: right;">3.86</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Crawford</td>
<td style="text-align: right;">58734</td>
<td style="text-align: right;">3.91</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fayette</td>
<td style="text-align: right;">55579</td>
<td style="text-align: right;">4.16</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adams</td>
<td style="text-align: right;">78975</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clarion</td>
<td style="text-align: right;">58690</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lycoming</td>
<td style="text-align: right;">63437</td>
<td style="text-align: right;">4.39</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Potter</td>
<td style="text-align: right;">56491</td>
<td style="text-align: right;">4.42</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bedford</td>
<td style="text-align: right;">58337</td>
<td style="text-align: right;">4.47</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: right;">57170</td>
<td style="text-align: right;">4.65</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Huntingdon</td>
<td style="text-align: right;">61300</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">McKean</td>
<td style="text-align: right;">57861</td>
<td style="text-align: right;">4.75</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Juniata</td>
<td style="text-align: right;">61915</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wayne</td>
<td style="text-align: right;">59240</td>
<td style="text-align: right;">4.79</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pike</td>
<td style="text-align: right;">76416</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Warren</td>
<td style="text-align: right;">57925</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carbon</td>
<td style="text-align: right;">64538</td>
<td style="text-align: right;">5.31</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Snyder</td>
<td style="text-align: right;">65914</td>
<td style="text-align: right;">5.56</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cameron</td>
<td style="text-align: right;">46186</td>
<td style="text-align: right;">5.64</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greene</td>
<td style="text-align: right;">66283</td>
<td style="text-align: right;">6.41</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elk</td>
<td style="text-align: right;">61672</td>
<td style="text-align: right;">6.63</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montour</td>
<td style="text-align: right;">72626</td>
<td style="text-align: right;">7.09</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Union</td>
<td style="text-align: right;">64914</td>
<td style="text-align: right;">7.32</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sullivan</td>
<td style="text-align: right;">62910</td>
<td style="text-align: right;">9.25</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Forest</td>
<td style="text-align: right;">46188</td>
<td style="text-align: right;">9.99</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><p><strong>Counties suitable for immediate algorithmic implementation:</strong> The 57 counties with high confidence data (MOE &lt; 5%) including major population centers like Allegheny, Philadelphia, Montgomery, Bucks, and Chester counties are appropriate for immediate algorithmic implementation. These counties have large populations, stable demographic patterns, and reliable census estimates that minimize the risk of algorithmic bias. Their robust data quality allows algorithms to make accurate assessments and resource allocations with minimal human oversight required.</p></li>
<li><p><strong>Counties requiring additional oversight:</strong> The 10 counties with moderate confidence data (MOE 5-10%) including Forest, Sullivan, Union, Montour, Elk, Warren, Carbon, Snyder, Cameron, and Greene require enhanced monitoring protocols. These counties should implement quarterly outcome reviews, establish appeal processes for algorithmic decisions, conduct periodic manual audits of allocation patterns, and maintain enhanced documentation of decision rationales. Additionally, these counties should have lower thresholds for triggering manual review of high-stakes decisions.</p></li>
<li><p><strong>Counties needing alternative approaches:</strong> While my analysis found no counties with low confidence data at the county level, the tract-level analysis reveals that demographic data quality issues require special attention across all counties. For areas with significant demographic uncertainty, alternative approaches should include: partnering with local community organizations for supplementary data collection, implementing mandatory manual review for decisions affecting minority communities, developing alternative indicators beyond census data (such as school enrollment data or local administrative records), and establishing community feedback mechanisms to validate algorithmic outcomes.</p></li>
</ol>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<ol type="1">
<li><p><strong>Geographic Clustering of Data Quality Issues:</strong> Are the counties with moderate confidence data (Forest, Sullivan, Cameron, etc.) geographically clustered in specific regions of Pennsylvania, and do they share common characteristics such as rural designation, distance from urban centers, or economic base? Understanding spatial patterns could help identify systematic factors affecting census data collection and inform targeted data quality improvement efforts.</p></li>
<li><p><strong>Demographic Data Reliability Across Different Community Types:</strong> How does the reliability of demographic data vary between urban, suburban, and rural census tracts, and are there specific thresholds of population size or demographic diversity below which data becomes systematically unreliable? This analysis could help establish evidence-based guidelines for when additional data collection or alternative assessment methods are needed.</p></li>
<li><p><strong>Impact of Data Quality on Service Delivery Outcomes:</strong> How do current social service allocation patterns correlate with data quality levels, and are communities with less reliable census data currently underserved relative to their documented needs? This longitudinal analysis could provide evidence of existing algorithmic bias and help quantify the potential impact of implementing data quality-aware decision systems.</p></li>
</ol>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on 09/22/2025</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version 4.5.1 - Census API key required for replication (obtain from https://api.census.gov/data/key_signup.html) - Complete code and documentation available at: [https://musa-5080-fall-2025.github.io/portfolio-setup-FANYANG0304/]</p>
<p><strong>Methodology Notes:</strong> County selection for detailed tract-level analysis was based on a stratified sampling approach, choosing counties from different reliability categories to ensure representation across data quality levels. Only Adams and Cameron counties were ultimately analyzed at the tract level due to the moderate confidence category having limited representation. MOE percentage calculations follow standard Census Bureau methodology (margin of error divided by estimate, multiplied by 100). Reliability categories were defined using commonly accepted thresholds in demographic analysis: High Confidence (&lt;5%), Moderate Confidence (5-10%), and Low Confidence (&gt;10%).</p>
<p><strong>Limitations:</strong> This analysis is limited to Pennsylvania and may not generalize to other states with different demographic or geographic characteristics. The tract-level analysis was constrained to only two counties, which may not fully represent the diversity of data quality issues across all Pennsylvania communities. The assignment focuses on specific demographic and income variables; other social and economic indicators may show different reliability patterns. The analysis uses a single time period (2022 ACS 5-year estimates) and does not account for temporal variations in data quality. Additionally, extreme MOE values (including infinite values) in some tract-level demographic estimates may indicate fundamental data collection challenges that require further investigation.</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox" checked="">All code chunks run without errors</label></li>
<li><label><input type="checkbox" checked="">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox" checked="">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox" checked="">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox" checked="">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox" checked="">Census API key is properly set</label></li>
<li><label><input type="checkbox" checked="">Document renders correctly to HTML</label></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>